models:
  - name: bronze_parking_violation_codes
    description: Raw data representing the violation coodes and their fees.
    columns:
      - name: violation_code
        description: '{{ doc("violation_code")}}'
        tests:
          - unique
          - not_null
          - generic_not_null
      - name: definition
        description: Description of the violation for a respective code.
      - name: manhattan_96th_st_below
        description: The fee in $USD for a violation on or below Manhattan 96th st.
      - name: all_other_areas
        description: The fee in $USD for a violation not on or below Manhattan 96th st.